# ============================================================
# Six-species flower Venn plots in the style of 花瓣图示例.png
# ============================================================
# Outputs:
#   analysis_codex/figures/FigS_6species_strict_milk_host_gene_flower_venn_Rstyle.*
#   analysis_codex/figures/FigS_6species_integrated_circRNA_host_gene_flower_venn_Rstyle.*
#
# Notes:
# - This is a manual 6-set flower Venn drawn with base grid graphics.
# - Region counts are read from the 63-region CSV files generated by
#   19_circACACA_result_figures.py.
# - Counts are exact Venn regions. The center label is the 6-way intersection.
# - Regions with zero count are explicitly retained in the input CSV; this plot
#   labels the main visible regions and keeps all counts available in the CSV.
# ============================================================

suppressPackageStartupMessages({
  library(grid)
})

find_project_root <- function() {
  script_file <- tryCatch(sys.frame(1)$ofile, error = function(e) NA_character_)
  if (is.null(script_file) || !length(script_file) || is.na(script_file)) {
    file_arg <- grep("^--file=", commandArgs(FALSE), value = TRUE)
    script_file <- if (length(file_arg)) sub("^--file=", "", file_arg[1]) else NA_character_
  }
  script_dir <- if (!is.na(script_file) && nzchar(script_file)) dirname(normalizePath(script_file, winslash = "/", mustWork = FALSE)) else NA_character_
  candidates <- c(
    getwd(),
    dirname(getwd()),
    if (!is.na(script_dir)) file.path(script_dir, "..", "..") else NA_character_
  )
  candidates <- candidates[!is.na(candidates)]
  candidates <- unique(normalizePath(candidates, winslash = "/", mustWork = FALSE))
  for (candidate in candidates) {
    if (dir.exists(file.path(candidate, "analysis_codex")) &&
        dir.exists(file.path(candidate, "New-analysis"))) {
      return(candidate)
    }
  }
  stop("Cannot find project root. Run from project root or analysis_codex/scripts.")
}

ROOT <- find_project_root()
OUT_DIR <- file.path(ROOT, "analysis_codex")
FIG_DIR <- file.path(OUT_DIR, "figures")
DATA_DIR <- file.path(OUT_DIR, "data", "output")
dir.create(FIG_DIR, recursive = TRUE, showWarnings = FALSE)

DATA_SPECIES <- c("hsa", "mma", "mmu", "mfu", "mpi", "rsi")
PLOT_SPECIES <- c("hsa", "mfu", "mma", "mmu", "mpi", "rsi")
SPECIES_LABELS <- c(
  hsa = "HSA",
  mfu = "MFU",
  mma = "MMA",
  mmu = "MMU",
  mpi = "MPI",
  rsi = "RSI"
)

PETAL_COLORS <- c(
  hsa = "#F8766D",
  mfu = "#FDAE61",
  mma = "#56B4E9",
  mmu = "#66C2A5",
  mpi = "#1F78B4",
  rsi = "#7B61FF"
)

read_regions <- function(path) {
  x <- read.csv(path, stringsAsFactors = FALSE)
  x$key <- x$species_combo
  x
}

get_count <- function(regions, combo, count_col = "exact_region_count") {
  combo <- combo[order(match(combo, DATA_SPECIES))]
  combo <- paste(combo, collapse = ";")
  hit <- regions[regions$key == combo, count_col]
  if (length(hit) == 0 || is.na(hit[1])) return(0L)
  as.integer(hit[1])
}

get_total <- function(summary_path, sp) {
  x <- read.csv(summary_path, stringsAsFactors = FALSE)
  hit <- x[x$species == sp, "set_size"]
  if (length(hit) == 0 || is.na(hit[1])) return(0L)
  as.integer(hit[1])
}

draw_petal <- function(x, y, width, height, rot, fill) {
  theta <- seq(0, 2 * pi, length.out = 240)
  xr <- (width / 2) * cos(theta)
  yr <- (height / 2) * sin(theta)
  a <- rot * pi / 180
  xp <- x + xr * cos(a) - yr * sin(a)
  yp <- y + xr * sin(a) + yr * cos(a)
  grid.polygon(
    x = unit(xp, "npc"),
    y = unit(yp, "npc"),
    gp = gpar(fill = adjustcolor(fill, alpha.f = 0.42),
              col = adjustcolor(fill, alpha.f = 0.90),
              lwd = 1.0)
  )
}

draw_label <- function(x, y, label, col = "black", fontsize = 8, fontface = "plain") {
  grid.text(
    label,
    x = unit(x, "npc"),
    y = unit(y, "npc"),
    gp = gpar(col = col, fontsize = fontsize, fontface = fontface)
  )
}

draw_region <- function(regions, combo, x, y, col = "black", fontsize = 7) {
  draw_label(x, y, get_count(regions, combo), col = col, fontsize = fontsize)
}

draw_flower <- function(region_file, summary_file, title, subtitle, output_stem) {
  regions <- read_regions(region_file)
  output_base <- file.path(FIG_DIR, output_stem)

  draw_page <- function() {
    grid.newpage()
    pushViewport(viewport(x = 0, y = 0, width = 1, height = 1,
                          just = c("left", "bottom")))

    # Petal geometry chosen to mimic 花瓣图示例.png.
    draw_petal(0.380, 0.600, 0.72, 0.34, -18, PETAL_COLORS["hsa"])
    draw_petal(0.500, 0.625, 0.34, 0.78, 0, PETAL_COLORS["mfu"])
    draw_petal(0.620, 0.600, 0.72, 0.34, 18, PETAL_COLORS["mma"])
    draw_petal(0.645, 0.405, 0.58, 0.35, -23, PETAL_COLORS["mmu"])
    draw_petal(0.500, 0.405, 0.37, 0.74, 90, PETAL_COLORS["mpi"])
    draw_petal(0.355, 0.405, 0.58, 0.35, 23, PETAL_COLORS["rsi"])

    # Outer species labels and single-set exact counts.
    draw_label(0.055, 0.790, "HSA", fontsize = 11, fontface = "bold")
    draw_label(0.500, 0.945, "MFU", fontsize = 11, fontface = "bold")
    draw_label(0.945, 0.720, "MMA", fontsize = 11, fontface = "bold")
    draw_label(0.915, 0.220, "MMU", fontsize = 11, fontface = "bold")
    draw_label(0.500, 0.035, "MPI", fontsize = 11, fontface = "bold", col = "red")
    draw_label(0.055, 0.220, "RSI", fontsize = 11, fontface = "bold")

    draw_region(regions, "hsa", 0.105, 0.650)
    draw_region(regions, "mfu", 0.550, 0.865)
    draw_region(regions, "mma", 0.885, 0.545)
    draw_region(regions, "mmu", 0.850, 0.270)
    draw_region(regions, "mpi", 0.500, 0.075, col = "red")
    draw_region(regions, "rsi", 0.140, 0.135)

    # Pairwise and selected higher-order regions, placed to match the example style.
    draw_region(regions, c("hsa", "mfu"), 0.300, 0.790)
    draw_region(regions, c("mfu", "mma"), 0.650, 0.760)
    draw_region(regions, c("mma", "mmu"), 0.800, 0.485)
    draw_region(regions, c("mmu", "mpi"), 0.640, 0.145)
    draw_region(regions, c("mpi", "rsi"), 0.365, 0.145)
    draw_region(regions, c("hsa", "rsi"), 0.140, 0.360)

    draw_region(regions, c("hsa", "mma"), 0.245, 0.665)
    draw_region(regions, c("mfu", "mmu"), 0.705, 0.560)
    draw_region(regions, c("mma", "mpi"), 0.725, 0.395)
    draw_region(regions, c("mmu", "rsi"), 0.255, 0.255)
    draw_region(regions, c("hsa", "mpi"), 0.205, 0.315)
    draw_region(regions, c("mfu", "rsi"), 0.225, 0.510)

    draw_region(regions, c("hsa", "mfu", "mma"), 0.390, 0.720)
    draw_region(regions, c("mfu", "mma", "mmu"), 0.725, 0.610)
    draw_region(regions, c("mma", "mmu", "mpi"), 0.735, 0.310)
    draw_region(regions, c("mmu", "mpi", "rsi"), 0.575, 0.190)
    draw_region(regions, c("hsa", "mpi", "rsi"), 0.250, 0.250)
    draw_region(regions, c("hsa", "mfu", "rsi"), 0.250, 0.610)

    draw_region(regions, c("hsa", "mfu", "mpi"), 0.330, 0.675)
    draw_region(regions, c("mfu", "mma", "mpi"), 0.650, 0.665)
    draw_region(regions, c("hsa", "mmu", "rsi"), 0.185, 0.425)
    draw_region(regions, c("mma", "mmu", "rsi"), 0.785, 0.405)
    draw_region(regions, c("hsa", "mma", "mpi"), 0.470, 0.700)
    draw_region(regions, c("mfu", "mmu", "rsi"), 0.525, 0.225)

    # 4-way and 5-way representative visible regions.
    draw_region(regions, c("hsa", "mfu", "mma", "mpi"), 0.540, 0.710)
    draw_region(regions, c("mfu", "mma", "mmu", "mpi"), 0.685, 0.540)
    draw_region(regions, c("hsa", "mmu", "mpi", "rsi"), 0.315, 0.235)
    draw_region(regions, c("hsa", "mfu", "mpi", "rsi"), 0.305, 0.535)
    draw_region(regions, c("hsa", "mma", "mmu", "rsi"), 0.735, 0.450)
    draw_region(regions, c("mfu", "mmu", "mpi", "rsi"), 0.500, 0.180)

    draw_region(regions, c("hsa", "mma", "mmu", "mpi", "rsi"), 0.500, 0.130)
    draw_region(regions, c("hsa", "mfu", "mmu", "mpi", "rsi"), 0.455, 0.165)
    draw_region(regions, c("hsa", "mfu", "mma", "mpi", "rsi"), 0.355, 0.745)
    draw_region(regions, c("hsa", "mfu", "mma", "mmu", "mpi"), 0.610, 0.745)
    draw_region(regions, c("hsa", "mfu", "mma", "mmu", "rsi"), 0.690, 0.630)
    draw_region(regions, c("mfu", "mma", "mmu", "mpi", "rsi"), 0.755, 0.505)

    # Center: exact 6-way intersection.
    center_count <- get_count(regions, DATA_SPECIES)
    draw_label(0.500, 0.500, center_count, fontsize = 16, fontface = "bold",
               col = ifelse(center_count == 0, "red", "black"))

    popViewport()
  }

  png(paste0(output_base, ".png"), width = 1800, height = 1800, res = 300)
  draw_page()
  dev.off()

  pdf(paste0(output_base, ".pdf"), width = 6, height = 6)
  draw_page()
  dev.off()

  tiff(paste0(output_base, ".tiff"), width = 1800, height = 1800,
       res = 300, compression = "lzw")
  draw_page()
  dev.off()

  message("Wrote: ", output_base, ".png/.pdf/.tiff")
}

draw_flower(
  region_file = file.path(DATA_DIR, "strict_milk_host_gene_6species_flower_regions.csv"),
  summary_file = file.path(DATA_DIR, "strict_milk_host_gene_6species_flower_species_set_summary.csv"),
  title = "Six-species flower Venn: strict milk host genes",
  subtitle = "Expressed circRNA host genes from this study's milk CIRCexplorer3 matrix",
  output_stem = "FigS_6species_strict_milk_host_gene_flower_venn_Rstyle"
)

draw_flower(
  region_file = file.path(DATA_DIR, "integrated_circRNA_host_gene_6species_flower_regions.csv"),
  summary_file = file.path(DATA_DIR, "integrated_circRNA_host_gene_6species_flower_species_set_summary.csv"),
  title = "Six-species flower Venn: integrated circRNA host-gene evidence",
  subtitle = "This study's milk circRNA host genes + circAtlas host genes + curated circACACA milk evidence",
  output_stem = "FigS_6species_integrated_circRNA_host_gene_flower_venn_Rstyle"
)
